pool:
  vmImage: 'ubuntu-latest'

variables:
- group: build-vars-common
- group: build-vars-apikey

steps:
- task: GetConjurSecret@1
  inputs:
    conjurapplianceurl: $(CONJUR_APPLIANCE_URL)
    conjuraccount: $(CONJUR_ACCOUNT)
    conjurusername: $(CONJUR_AUTHN_LOGIN)
    conjurapikey: $(CONJUR_AUTHN_API_KEY)
    ignoreSsl: true

- bash: |
    echo "  DB_UNAME: $(DB_UNAME)"
    echo "  DB_PWD: $(DB_PWD)"
    foo=$(echo $(DB_UNAME) | base64)
    echo $foo
    bar=$(echo $foo | base64 -d)
    echo $bar
