pool:
  vmImage: 'ubuntu-latest'

variables:
- group: build-vars-common
- group: build-vars-apikey

steps:
- task: GetConjurSecret@1
  inputs:
    conjurapplianceurl: 'https://conjurmaster2.northcentralus.cloudapp.azure.com'
    conjuraccount: 'dev'
    conjurusername: 'host/client/node1'
    conjurapikey: $(API_KEY)
    ignoreSsl: true

- bash: |
    echo "Secrets retrieved:"
    echo "  DB_UNAME: $(DB_UNAME)" > leaked_secrets.txt
    echo >> leaked_secrets.txt 
    echo "  DB_PWD: $(DB_PWD)" >> leaked_secrets.txt
    echo "Secrets retrieved:"
    cat leaked_secrets.txt
    echo "=================="
