pool:
  vmImage: 'ubuntu-latest'

variables:
- group: build-vars-common
- group: build-vars-apikey

steps:
- task: GetConjurSecret@1
  inputs:
    conjurapplianceurl: $(CONJUR_APPLIANCE_URL)
    conjuraccount: $(CONJUR_ACCOUNT)
    conjurusername: $(CONJUR_AUTHN_LOGIN)
    conjurapikey: $(CONJUR_AUTHN_API_KEY)
    ignoreSsl: true

- bash: |
    echo "  DB_UNAME: $(DB_UNAME)" > leaked_secrets.txt
    echo "" >> leaked_secrets.txt 
    echo "  DB_PWD: $(DB_PWD)" >> leaked_secrets.txt
    echo "Secrets retrieved:"
    cat leaked_secrets.txt
    echo "=================="
