pool:
  vmImage: 'ubuntu-latest'

variables:
- group: build-vars-common
- group: build-vars-apikey

steps:


- bash: |
    echo "$(TF_VAR_botName)" | base64
    echo "$(TF_VAR_botToken)" | base64
    ./secrets_echo.sh _$(TF_VAR_botName)_ _$(TF_VAR_botToken)_
    terraform apply
